services:
  - type: web
    name: eduvox-web-api
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: eduvox-alexa
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python -m backend.scripts.run_alexa_server
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: worker
    name: eduvox-program-worker
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python -m backend.scripts.run_program_worker
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
